### ISSUE TITLE
fmt, lint & vet

### ISSUE THREAD

**Issue by josephholsten** [bobtfish/go-nsone-api#5]
I'm working on updating to remove as many lint and vet warnings without breaking API compat.

I'd like to know if you're interested in breaking API compat to make vet happy, eg:
* `Id` -> `ID`
* `Dns` -> `DNS`
* `Ttl` -> `TTL`
* removing `_` from public fields

**Comment by josephholsten** [comment]
@sarguru ^^

**Comment by josephholsten** [comment]
see #6

**Comment by bobtfish** [comment]
I'm OK with breaking compat, the only upstream client is our Terraform provider, and we can happily change that in lockstep.
